/*
* generated by Xtext
*/
package org.xtext.pipes.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.pipes.services.PipesGrammarAccess;

public class PipesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PipesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.pipes.parser.antlr.internal.InternalPipesParser createParser(XtextTokenStream stream) {
		return new org.xtext.pipes.parser.antlr.internal.InternalPipesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PipesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PipesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
