/*
* generated by Xtext
*/
package org.xtext.example.pipes.ui.contentassist;

import org.xtext.example.pipes.ui.contentassist.AbstractPipesProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PipesProposalProvider extends AbstractPipesProposalProvider {

}
