/*
* generated by Xtext
*/

package org.xtext.pipes.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class PipesGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cElementsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cElementsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cElementsGUIDElementParserRuleCall_3_2_0 = (RuleCall)cElementsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cElementsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cElementsGUIDElementParserRuleCall_3_3_1_0 = (RuleCall)cElementsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Model:
		//	{Model} "Model" "{" ("elements" "{" elements+=GUIDElement ("," elements+=GUIDElement)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Model} "Model" "{" ("elements" "{" elements+=GUIDElement ("," elements+=GUIDElement)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }

		//"Model"
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("elements" "{" elements+=GUIDElement ("," elements+=GUIDElement)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"elements"
		public Keyword getElementsKeyword_3_0() { return cElementsKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//elements+=GUIDElement
		public Assignment getElementsAssignment_3_2() { return cElementsAssignment_3_2; }

		//GUIDElement
		public RuleCall getElementsGUIDElementParserRuleCall_3_2_0() { return cElementsGUIDElementParserRuleCall_3_2_0; }

		//("," elements+=GUIDElement)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//elements+=GUIDElement
		public Assignment getElementsAssignment_3_3_1() { return cElementsAssignment_3_3_1; }

		//GUIDElement
		public RuleCall getElementsGUIDElementParserRuleCall_3_3_1_0() { return cElementsGUIDElementParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class GUIDElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GUIDElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGUIDElement_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWallParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cOpeningParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cFlowSegmentParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//GUIDElement:
		//	GUIDElement_Impl | Wall | Opening | FlowSegment;
		public ParserRule getRule() { return rule; }

		//GUIDElement_Impl | Wall | Opening | FlowSegment
		public Alternatives getAlternatives() { return cAlternatives; }

		//GUIDElement_Impl
		public RuleCall getGUIDElement_ImplParserRuleCall_0() { return cGUIDElement_ImplParserRuleCall_0; }

		//Wall
		public RuleCall getWallParserRuleCall_1() { return cWallParserRuleCall_1; }

		//Opening
		public RuleCall getOpeningParserRuleCall_2() { return cOpeningParserRuleCall_2; }

		//FlowSegment
		public RuleCall getFlowSegmentParserRuleCall_3() { return cFlowSegmentParserRuleCall_3; }
	}

	public class GUIDElement_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GUIDElement_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGUIDElementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGUIDElementKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cGUIDKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cGUIDAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cGUIDEStringParserRuleCall_3_1_0 = (RuleCall)cGUIDAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_4_1_0 = (RuleCall)cNameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//GUIDElement_Impl returns GUIDElement:
		//	{GUIDElement} "GUIDElement" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)?
		//	"}";
		public ParserRule getRule() { return rule; }

		//{GUIDElement} "GUIDElement" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{GUIDElement}
		public Action getGUIDElementAction_0() { return cGUIDElementAction_0; }

		//"GUIDElement"
		public Keyword getGUIDElementKeyword_1() { return cGUIDElementKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("GUID" GUID=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"GUID"
		public Keyword getGUIDKeyword_3_0() { return cGUIDKeyword_3_0; }

		//GUID=EString
		public Assignment getGUIDAssignment_3_1() { return cGUIDAssignment_3_1; }

		//EString
		public RuleCall getGUIDEStringParserRuleCall_3_1_0() { return cGUIDEStringParserRuleCall_3_1_0; }

		//("Name" Name=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"Name"
		public Keyword getNameKeyword_4_0() { return cNameKeyword_4_0; }

		//Name=EString
		public Assignment getNameAssignment_4_1() { return cNameAssignment_4_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_4_1_0() { return cNameEStringParserRuleCall_4_1_0; }

		//("Description" Description=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"Description"
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }

		//Description=EString
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_5_1_0() { return cDescriptionEStringParserRuleCall_5_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class WallElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Wall");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWallKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cGUIDKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cGUIDAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cGUIDEStringParserRuleCall_2_1_0 = (RuleCall)cGUIDAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cPlacementKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPlacementAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPlacementLocalPlacementParserRuleCall_6_0 = (RuleCall)cPlacementAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Wall:
		//	"Wall" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
		//	placement=LocalPlacement "}";
		public ParserRule getRule() { return rule; }

		//"Wall" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
		//placement=LocalPlacement "}"
		public Group getGroup() { return cGroup; }

		//"Wall"
		public Keyword getWallKeyword_0() { return cWallKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("GUID" GUID=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"GUID"
		public Keyword getGUIDKeyword_2_0() { return cGUIDKeyword_2_0; }

		//GUID=EString
		public Assignment getGUIDAssignment_2_1() { return cGUIDAssignment_2_1; }

		//EString
		public RuleCall getGUIDEStringParserRuleCall_2_1_0() { return cGUIDEStringParserRuleCall_2_1_0; }

		//("Name" Name=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"Name"
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }

		//Name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }

		//("Description" Description=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"Description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//Description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }

		//"placement"
		public Keyword getPlacementKeyword_5() { return cPlacementKeyword_5; }

		//placement=LocalPlacement
		public Assignment getPlacementAssignment_6() { return cPlacementAssignment_6; }

		//LocalPlacement
		public RuleCall getPlacementLocalPlacementParserRuleCall_6_0() { return cPlacementLocalPlacementParserRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class OpeningElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Opening");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpeningKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cGUIDKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cGUIDAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cGUIDEStringParserRuleCall_2_1_0 = (RuleCall)cGUIDAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cPlacementKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPlacementAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPlacementLocalPlacementParserRuleCall_6_0 = (RuleCall)cPlacementAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cWallsKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cWallsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cWallsWallParserRuleCall_7_2_0 = (RuleCall)cWallsAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cWallsAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cWallsWallParserRuleCall_7_3_1_0 = (RuleCall)cWallsAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Opening:
		//	"Opening" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
		//	placement=LocalPlacement ("walls" "{" walls+=Wall ("," walls+=Wall)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"Opening" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
		//placement=LocalPlacement ("walls" "{" walls+=Wall ("," walls+=Wall)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"Opening"
		public Keyword getOpeningKeyword_0() { return cOpeningKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("GUID" GUID=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"GUID"
		public Keyword getGUIDKeyword_2_0() { return cGUIDKeyword_2_0; }

		//GUID=EString
		public Assignment getGUIDAssignment_2_1() { return cGUIDAssignment_2_1; }

		//EString
		public RuleCall getGUIDEStringParserRuleCall_2_1_0() { return cGUIDEStringParserRuleCall_2_1_0; }

		//("Name" Name=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"Name"
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }

		//Name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }

		//("Description" Description=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"Description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//Description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }

		//"placement"
		public Keyword getPlacementKeyword_5() { return cPlacementKeyword_5; }

		//placement=LocalPlacement
		public Assignment getPlacementAssignment_6() { return cPlacementAssignment_6; }

		//LocalPlacement
		public RuleCall getPlacementLocalPlacementParserRuleCall_6_0() { return cPlacementLocalPlacementParserRuleCall_6_0; }

		//("walls" "{" walls+=Wall ("," walls+=Wall)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"walls"
		public Keyword getWallsKeyword_7_0() { return cWallsKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//walls+=Wall
		public Assignment getWallsAssignment_7_2() { return cWallsAssignment_7_2; }

		//Wall
		public RuleCall getWallsWallParserRuleCall_7_2_0() { return cWallsWallParserRuleCall_7_2_0; }

		//("," walls+=Wall)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//walls+=Wall
		public Assignment getWallsAssignment_7_3_1() { return cWallsAssignment_7_3_1; }

		//Wall
		public RuleCall getWallsWallParserRuleCall_7_3_1_0() { return cWallsWallParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class FlowSegmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FlowSegment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFlowSegmentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cGUIDKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cGUIDAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cGUIDEStringParserRuleCall_2_1_0 = (RuleCall)cGUIDAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNameKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDescriptionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDescriptionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_4_1_0 = (RuleCall)cDescriptionAssignment_4_1.eContents().get(0);
		private final Keyword cPlacementKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPlacementAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPlacementLocalPlacementParserRuleCall_6_0 = (RuleCall)cPlacementAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//FlowSegment:
		//	"FlowSegment" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
		//	placement=LocalPlacement "}";
		public ParserRule getRule() { return rule; }

		//"FlowSegment" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
		//placement=LocalPlacement "}"
		public Group getGroup() { return cGroup; }

		//"FlowSegment"
		public Keyword getFlowSegmentKeyword_0() { return cFlowSegmentKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("GUID" GUID=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"GUID"
		public Keyword getGUIDKeyword_2_0() { return cGUIDKeyword_2_0; }

		//GUID=EString
		public Assignment getGUIDAssignment_2_1() { return cGUIDAssignment_2_1; }

		//EString
		public RuleCall getGUIDEStringParserRuleCall_2_1_0() { return cGUIDEStringParserRuleCall_2_1_0; }

		//("Name" Name=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"Name"
		public Keyword getNameKeyword_3_0() { return cNameKeyword_3_0; }

		//Name=EString
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_3_1_0() { return cNameEStringParserRuleCall_3_1_0; }

		//("Description" Description=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"Description"
		public Keyword getDescriptionKeyword_4_0() { return cDescriptionKeyword_4_0; }

		//Description=EString
		public Assignment getDescriptionAssignment_4_1() { return cDescriptionAssignment_4_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_4_1_0() { return cDescriptionEStringParserRuleCall_4_1_0; }

		//"placement"
		public Keyword getPlacementKeyword_5() { return cPlacementKeyword_5; }

		//placement=LocalPlacement
		public Assignment getPlacementAssignment_6() { return cPlacementAssignment_6; }

		//LocalPlacement
		public RuleCall getPlacementLocalPlacementParserRuleCall_6_0() { return cPlacementLocalPlacementParserRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class LocalPlacementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LocalPlacement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cLocalPlacementAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLocalPlacementKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRelativeToKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cRelativeToAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cRelativeToLocalPlacementCrossReference_3_1_0 = (CrossReference)cRelativeToAssignment_3_1.eContents().get(0);
		private final RuleCall cRelativeToLocalPlacementEStringParserRuleCall_3_1_0_1 = (RuleCall)cRelativeToLocalPlacementCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAxis2placement3dKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAxis2placement3dAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAxis2placement3dAxis2Placement3DParserRuleCall_4_1_0 = (RuleCall)cAxis2placement3dAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//LocalPlacement:
		//	{LocalPlacement} "LocalPlacement" "{" ("relativeTo" relativeTo=[LocalPlacement|EString])? ("axis2placement3d"
		//	axis2placement3d=Axis2Placement3D)? "}";
		public ParserRule getRule() { return rule; }

		//{LocalPlacement} "LocalPlacement" "{" ("relativeTo" relativeTo=[LocalPlacement|EString])? ("axis2placement3d"
		//axis2placement3d=Axis2Placement3D)? "}"
		public Group getGroup() { return cGroup; }

		//{LocalPlacement}
		public Action getLocalPlacementAction_0() { return cLocalPlacementAction_0; }

		//"LocalPlacement"
		public Keyword getLocalPlacementKeyword_1() { return cLocalPlacementKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("relativeTo" relativeTo=[LocalPlacement|EString])?
		public Group getGroup_3() { return cGroup_3; }

		//"relativeTo"
		public Keyword getRelativeToKeyword_3_0() { return cRelativeToKeyword_3_0; }

		//relativeTo=[LocalPlacement|EString]
		public Assignment getRelativeToAssignment_3_1() { return cRelativeToAssignment_3_1; }

		//[LocalPlacement|EString]
		public CrossReference getRelativeToLocalPlacementCrossReference_3_1_0() { return cRelativeToLocalPlacementCrossReference_3_1_0; }

		//EString
		public RuleCall getRelativeToLocalPlacementEStringParserRuleCall_3_1_0_1() { return cRelativeToLocalPlacementEStringParserRuleCall_3_1_0_1; }

		//("axis2placement3d" axis2placement3d=Axis2Placement3D)?
		public Group getGroup_4() { return cGroup_4; }

		//"axis2placement3d"
		public Keyword getAxis2placement3dKeyword_4_0() { return cAxis2placement3dKeyword_4_0; }

		//axis2placement3d=Axis2Placement3D
		public Assignment getAxis2placement3dAssignment_4_1() { return cAxis2placement3dAssignment_4_1; }

		//Axis2Placement3D
		public RuleCall getAxis2placement3dAxis2Placement3DParserRuleCall_4_1_0() { return cAxis2placement3dAxis2Placement3DParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class Axis2Placement3DElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Axis2Placement3D");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAxis2Placement3DKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCartesianXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCartesianXAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCartesianXEDoubleParserRuleCall_3_0 = (RuleCall)cCartesianXAssignment_3.eContents().get(0);
		private final Keyword cCartesianYKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cCartesianYAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cCartesianYEDoubleParserRuleCall_5_0 = (RuleCall)cCartesianYAssignment_5.eContents().get(0);
		private final Keyword cCartesianZKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCartesianZAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCartesianZEDoubleParserRuleCall_7_0 = (RuleCall)cCartesianZAssignment_7.eContents().get(0);
		private final Keyword cAxisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cAxisAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cAxisDirectionParserRuleCall_9_0 = (RuleCall)cAxisAssignment_9.eContents().get(0);
		private final Keyword cRefDirectionKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cRefDirectionAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cRefDirectionDirectionParserRuleCall_11_0 = (RuleCall)cRefDirectionAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Axis2Placement3D:
		//	"Axis2Placement3D" "{" "cartesianX" cartesianX=EDouble "cartesianY" cartesianY=EDouble "cartesianZ" cartesianZ=EDouble
		//	"axis" axis=Direction "refDirection" refDirection=Direction "}";
		public ParserRule getRule() { return rule; }

		//"Axis2Placement3D" "{" "cartesianX" cartesianX=EDouble "cartesianY" cartesianY=EDouble "cartesianZ" cartesianZ=EDouble
		//"axis" axis=Direction "refDirection" refDirection=Direction "}"
		public Group getGroup() { return cGroup; }

		//"Axis2Placement3D"
		public Keyword getAxis2Placement3DKeyword_0() { return cAxis2Placement3DKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"cartesianX"
		public Keyword getCartesianXKeyword_2() { return cCartesianXKeyword_2; }

		//cartesianX=EDouble
		public Assignment getCartesianXAssignment_3() { return cCartesianXAssignment_3; }

		//EDouble
		public RuleCall getCartesianXEDoubleParserRuleCall_3_0() { return cCartesianXEDoubleParserRuleCall_3_0; }

		//"cartesianY"
		public Keyword getCartesianYKeyword_4() { return cCartesianYKeyword_4; }

		//cartesianY=EDouble
		public Assignment getCartesianYAssignment_5() { return cCartesianYAssignment_5; }

		//EDouble
		public RuleCall getCartesianYEDoubleParserRuleCall_5_0() { return cCartesianYEDoubleParserRuleCall_5_0; }

		//"cartesianZ"
		public Keyword getCartesianZKeyword_6() { return cCartesianZKeyword_6; }

		//cartesianZ=EDouble
		public Assignment getCartesianZAssignment_7() { return cCartesianZAssignment_7; }

		//EDouble
		public RuleCall getCartesianZEDoubleParserRuleCall_7_0() { return cCartesianZEDoubleParserRuleCall_7_0; }

		//"axis"
		public Keyword getAxisKeyword_8() { return cAxisKeyword_8; }

		//axis=Direction
		public Assignment getAxisAssignment_9() { return cAxisAssignment_9; }

		//Direction
		public RuleCall getAxisDirectionParserRuleCall_9_0() { return cAxisDirectionParserRuleCall_9_0; }

		//"refDirection"
		public Keyword getRefDirectionKeyword_10() { return cRefDirectionKeyword_10; }

		//refDirection=Direction
		public Assignment getRefDirectionAssignment_11() { return cRefDirectionAssignment_11; }

		//Direction
		public RuleCall getRefDirectionDirectionParserRuleCall_11_0() { return cRefDirectionDirectionParserRuleCall_11_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class EDoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EDouble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EDouble returns ecore::EDouble:
		//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
		public ParserRule getRule() { return rule; }

		//"-"? INT? "." INT (("E" | "e") "-"? INT)?
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }

		//"."
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }

		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }

		//(("E" | "e") "-"? INT)?
		public Group getGroup_4() { return cGroup_4; }

		//"E" | "e"
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }

		//"E"
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }

		//"e"
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }

		//"-"?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}

	public class DirectionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Direction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDirectionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cXKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cXAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cXEDoubleParserRuleCall_3_0 = (RuleCall)cXAssignment_3.eContents().get(0);
		private final Keyword cYKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cYAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cYEDoubleParserRuleCall_5_0 = (RuleCall)cYAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cZKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cZAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cZEDoubleParserRuleCall_6_1_0 = (RuleCall)cZAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Direction:
		//	"Direction" "{" "x" x=EDouble "y" y=EDouble ("z" z=EDouble)? "}";
		public ParserRule getRule() { return rule; }

		//"Direction" "{" "x" x=EDouble "y" y=EDouble ("z" z=EDouble)? "}"
		public Group getGroup() { return cGroup; }

		//"Direction"
		public Keyword getDirectionKeyword_0() { return cDirectionKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"x"
		public Keyword getXKeyword_2() { return cXKeyword_2; }

		//x=EDouble
		public Assignment getXAssignment_3() { return cXAssignment_3; }

		//EDouble
		public RuleCall getXEDoubleParserRuleCall_3_0() { return cXEDoubleParserRuleCall_3_0; }

		//"y"
		public Keyword getYKeyword_4() { return cYKeyword_4; }

		//y=EDouble
		public Assignment getYAssignment_5() { return cYAssignment_5; }

		//EDouble
		public RuleCall getYEDoubleParserRuleCall_5_0() { return cYEDoubleParserRuleCall_5_0; }

		//("z" z=EDouble)?
		public Group getGroup_6() { return cGroup_6; }

		//"z"
		public Keyword getZKeyword_6_0() { return cZKeyword_6_0; }

		//z=EDouble
		public Assignment getZAssignment_6_1() { return cZAssignment_6_1; }

		//EDouble
		public RuleCall getZEDoubleParserRuleCall_6_1_0() { return cZEDoubleParserRuleCall_6_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private ModelElements pModel;
	private GUIDElementElements pGUIDElement;
	private GUIDElement_ImplElements pGUIDElement_Impl;
	private EStringElements pEString;
	private WallElements pWall;
	private OpeningElements pOpening;
	private FlowSegmentElements pFlowSegment;
	private LocalPlacementElements pLocalPlacement;
	private Axis2Placement3DElements pAxis2Placement3D;
	private EDoubleElements pEDouble;
	private DirectionElements pDirection;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public PipesGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.pipes.Pipes".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	{Model} "Model" "{" ("elements" "{" elements+=GUIDElement ("," elements+=GUIDElement)* "}")? "}";
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//GUIDElement:
	//	GUIDElement_Impl | Wall | Opening | FlowSegment;
	public GUIDElementElements getGUIDElementAccess() {
		return (pGUIDElement != null) ? pGUIDElement : (pGUIDElement = new GUIDElementElements());
	}
	
	public ParserRule getGUIDElementRule() {
		return getGUIDElementAccess().getRule();
	}

	//GUIDElement_Impl returns GUIDElement:
	//	{GUIDElement} "GUIDElement" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)?
	//	"}";
	public GUIDElement_ImplElements getGUIDElement_ImplAccess() {
		return (pGUIDElement_Impl != null) ? pGUIDElement_Impl : (pGUIDElement_Impl = new GUIDElement_ImplElements());
	}
	
	public ParserRule getGUIDElement_ImplRule() {
		return getGUIDElement_ImplAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Wall:
	//	"Wall" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
	//	placement=LocalPlacement "}";
	public WallElements getWallAccess() {
		return (pWall != null) ? pWall : (pWall = new WallElements());
	}
	
	public ParserRule getWallRule() {
		return getWallAccess().getRule();
	}

	//Opening:
	//	"Opening" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
	//	placement=LocalPlacement ("walls" "{" walls+=Wall ("," walls+=Wall)* "}")? "}";
	public OpeningElements getOpeningAccess() {
		return (pOpening != null) ? pOpening : (pOpening = new OpeningElements());
	}
	
	public ParserRule getOpeningRule() {
		return getOpeningAccess().getRule();
	}

	//FlowSegment:
	//	"FlowSegment" "{" ("GUID" GUID=EString)? ("Name" Name=EString)? ("Description" Description=EString)? "placement"
	//	placement=LocalPlacement "}";
	public FlowSegmentElements getFlowSegmentAccess() {
		return (pFlowSegment != null) ? pFlowSegment : (pFlowSegment = new FlowSegmentElements());
	}
	
	public ParserRule getFlowSegmentRule() {
		return getFlowSegmentAccess().getRule();
	}

	//LocalPlacement:
	//	{LocalPlacement} "LocalPlacement" "{" ("relativeTo" relativeTo=[LocalPlacement|EString])? ("axis2placement3d"
	//	axis2placement3d=Axis2Placement3D)? "}";
	public LocalPlacementElements getLocalPlacementAccess() {
		return (pLocalPlacement != null) ? pLocalPlacement : (pLocalPlacement = new LocalPlacementElements());
	}
	
	public ParserRule getLocalPlacementRule() {
		return getLocalPlacementAccess().getRule();
	}

	//Axis2Placement3D:
	//	"Axis2Placement3D" "{" "cartesianX" cartesianX=EDouble "cartesianY" cartesianY=EDouble "cartesianZ" cartesianZ=EDouble
	//	"axis" axis=Direction "refDirection" refDirection=Direction "}";
	public Axis2Placement3DElements getAxis2Placement3DAccess() {
		return (pAxis2Placement3D != null) ? pAxis2Placement3D : (pAxis2Placement3D = new Axis2Placement3DElements());
	}
	
	public ParserRule getAxis2Placement3DRule() {
		return getAxis2Placement3DAccess().getRule();
	}

	//EDouble returns ecore::EDouble:
	//	"-"? INT? "." INT (("E" | "e") "-"? INT)?;
	public EDoubleElements getEDoubleAccess() {
		return (pEDouble != null) ? pEDouble : (pEDouble = new EDoubleElements());
	}
	
	public ParserRule getEDoubleRule() {
		return getEDoubleAccess().getRule();
	}

	//Direction:
	//	"Direction" "{" "x" x=EDouble "y" y=EDouble ("z" z=EDouble)? "}";
	public DirectionElements getDirectionAccess() {
		return (pDirection != null) ? pDirection : (pDirection = new DirectionElements());
	}
	
	public ParserRule getDirectionRule() {
		return getDirectionAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
