/*
* generated by Xtext
*/
package org.xtext.example.light.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.light.services.LightGrammarAccess;

public class LightParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LightGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.light.parser.antlr.internal.InternalLightParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.light.parser.antlr.internal.InternalLightParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Main";
	}
	
	public LightGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LightGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
