/*
 * generated by Xtext
 */
package org.xtext.example.pipes.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.pipes.ui.internal.PipesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PipesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PipesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PipesActivator.getInstance().getInjector(PipesActivator.ORG_XTEXT_EXAMPLE_PIPES_PIPES);
	}
	
}
