/*
* generated by Xtext
*/
package org.xtext.example.light.ui.contentassist;

import org.xtext.example.light.ui.contentassist.AbstractLightProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LightProposalProvider extends AbstractLightProposalProvider {

}
