/*
 * generated by Xtext
 */
package org.xtext.example.pipes;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PipesRuntimeModule extends org.xtext.example.pipes.AbstractPipesRuntimeModule {

}
