/*
 * generated by Xtext
 */
package org.xtext.example.light.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LightUiModule extends org.xtext.example.light.ui.AbstractLightUiModule {
	public LightUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
