/*
 * generated by Xtext
 */
package org.xtext.example.light.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.light.ui.internal.LightActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LightExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LightActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LightActivator.getInstance().getInjector(LightActivator.ORG_XTEXT_EXAMPLE_LIGHT_LIGHT);
	}
	
}
