/*
 * generated by Xtext
 */
package org.xtext.example.pipes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PipesUiModule extends org.xtext.example.pipes.ui.AbstractPipesUiModule {
	public PipesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
